include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_VAPOROS_VAPORSHELL_PROGNAME)
PRIORITY  = $(CONFIG_VAPOROS_VAPORSHELL_PRIORITY)
STACKSIZE = $(CONFIG_VAPOROS_VAPORSHELL_STACKSIZE)
MODULE    = $(CONFIG_VAPOROS_VAPORSHELL)

MAINSRC = vaporshell_main.c

include $(APPDIR)/Application.mk
