# In POSIX mode ${@...} and ${*...} work on the parameters joined into one string, as in dash;
# slices, replacement and case changes do not exist.
( set -- foo.txt bar.txt; IFS=:; echo "${@}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${*}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo ${#@} ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo ${#*} ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@:-d}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@-d}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@:+alt}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@+alt}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@#foo}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@%.txt}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@%%.*}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${*##*.}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@:2}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@/o/0}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@^^}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@@Q}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@:=x}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@=x}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@:?m}" ) 2>/dev/null; echo "rc=$?"
( set -- foo.txt bar.txt; IFS=:; echo "${@?m}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${*}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo ${#@} ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo ${#*} ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@:-d}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@-d}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@:+alt}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@+alt}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@#foo}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@%.txt}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@%%.*}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${*##*.}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@:2}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@/o/0}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@^^}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@@Q}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@:=x}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@=x}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@:?m}" ) 2>/dev/null; echo "rc=$?"
( set --; IFS=:; echo "${@?m}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${*}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo ${#@} ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo ${#*} ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@:-d}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@-d}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@:+alt}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@+alt}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@#foo}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@%.txt}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@%%.*}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${*##*.}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@:2}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@/o/0}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@^^}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@@Q}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@:=x}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@=x}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@:?m}" ) 2>/dev/null; echo "rc=$?"
( set -- a; IFS=:; echo "${@?m}" ) 2>/dev/null; echo "rc=$?"
